spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:mysql://localhost:3306/constractionproject
    #  ${DATASOURCE_URL}
    username: root
    #  ${DATASOURCE_USERNAME}
    password: a2009300babych
    #  ${DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml

logging:
  level:
    root: warn


server:
  port: 8080

