spring:

  datasource:
    url: jdbc:mysql://localhost:3306/constraction_project
    username: root
    password: a2009300babych

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

  sql:
    init:
      mode: always
      schema-locations: classpath:db/changelog/schema.sql
      data-locations: classpath:db/changelog/data.sql



server:
  port: 8080
