spring:

  application:
    banner-mode: off

  datasource:
    url: jdbc:mysql://localhost:3306/constraction_project
    username: root
    password: a2009300babych
    data-source-properties:
      data:
        - classpath:db/changelog/data.sql
      schema:
        - classpath:db/changelog/schema.sql

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

  sql:
    init:
      mode: always

  liquibase:
    enabled: true

server:
  port: 8080
