spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:mysql://localhost:3306/construction_project
    username: root
    password: a2009300babych

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml

logging:
  level:
    root: debug


server:
  port: 8080

